name: 'osu!profile'
author: newtykins
description: 'GitHub action to inject information about your osu! profile to your readme'

inputs:
  ID:
    description: 'The ID of the osu! account to lookup'
    required: true
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'activity'
  color: 'purple'
