name: 'osu! rank'
author: newtykins
description: 'Show off your osu! rank in your profile readme!'
inputs:
  ID:
    description: 'The ID of the osu! account to lookup'
    required: true
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'index.js'
